# This is a basic workflow to help you get started with Actions

name: "GitHub Actions SMZDM Bot"

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    # branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '55 14 * * *'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      # Runs a set of commands using the runners shell
      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Working
        env:
          COOKIES: '__ckguid=Ewo4HQj5gxE8RyQ7QCaQbF5; device_id=2130706433162573996234645313623518350a5b481b45cdbcdc875635; r_sort_type=score; __jsluid_s=ce2f66ea6f10a273e9d6db1cc4c73186; __gads=ID=6bb832a6db895202:T=1628130217:S=ALNI_MauP8nFXlf-kkikqSxeCX50wty89g; homepage_sug=a; _ga=GA1.2.266293342.1625739964; _ga_09SRZM2FDD=GS1.1.1635918680.7.1.1635918808.0; footer_floating_layer=0; ad_date=1; ad_json_feed=%7B%7D; Hm_lvt_9b7ac3d38f30fe89ff0b8a0546904e58=1635918681,1638325841; _zdmA.vid=*; sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%2217a85a72e737db-04ef1ebace3244-30614701-2073600-17a85a72e749b3%22%2C%22first_id%22%3A%22%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E5%BC%95%E8%8D%90%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC%22%2C%22%24latest_referrer%22%3A%22https%3A%2F%2Fgithub.com%2Fhuicando%2Fsmzdm_bot%22%7D%2C%22%24device_id%22%3A%2217a85a72e737db-04ef1ebace3244-30614701-2073600-17a85a72e749b3%22%7D; sess=AT-zOpnslQCh88sf66fcwFbNGyQLrQnqi%2FFZT2mraRGIVu5sOwwltYAjErCFOXfy89f8Lho6yhQB4GGWs%2FOOfZ6evLFewQ%2BkiHXo5uaAIq0GpiY0pNJu%2BxcndJr; user=user%3A5726938956%7C5726938956; _zdmA.uid=ZDMA.6VC1SWMnq.1638326037.2419200; Hm_lpvt_9b7ac3d38f30fe89ff0b8a0546904e58=1638326037; smzdm_id=5726938956; bannerCounter=%5B%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A2%2C%22surplus%22%3A1%7D%2C%7B%22number%22%3A0%2C%22surplus%22%3A1%7D%5D; _zdmA.time=1638326038679.0.https%3A%2F%2Fwww.smzdm.com%2F'
          SERVERCHAN_SECRETKEY: ${{ secrets.SERVERCHAN_SECRETKEY }}
        run: python main.py #>SMZDM_Bot.log
